DROP TABLE IF EXISTS reservation;

CREATE TABLE reservation (
    id INTEGER NOT NULL AUTO_INCREMENT,
    date DATE NOT NULL,
    time TIME NOT NULL,
    name VARCHAR(20) NOT NULL,
    PRIMARY KEY(id)
);

DROP TABLE IF EXISTS themes;

CREATE TABLE themes (
     id INTEGER NOT NULL AUTO_INCREMENT,
     name VARCHAR(100) NOT NULL,
     desc TEXT NOT NULL,
     price INTEGER NOT NULL,
     PRIMARY KEY(id)
);